name: advancedkeepinventory
version: '1.0'
main: io.github.howardtren.advancedkeepinventory.Advancedkeepinventory
api-version: '1.21'
load: STARTUP
authors: [ Howard Tren ]
description: Advanced Keep Inventory Plugin
website: io.github.howardtren

commands:
  aki:
    description: Advanced Keep Inventory
    permission: aki.manage
permission:
  aki.manage:
    description: Advanced Keep Inventory
    default: false